server:
  port: 8083

spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:3000"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true
      discovery:
        locator:
          enabled: true
      routes:
        - id: productCatalogus-service
          uri: lb://productCatalogus-service
          predicates:
            - Path=/product/**
          filters:
            - RewritePath=/product/(?<path>.*), /$\{path}
        - id: winkelwagen-service
          uri: lb://winkelwagen-service
          predicates:
            - Path=/winkelwagen/**
          filters:
            - RewritePath=/winkelwagen/(?<path>.*), /$\{path}
        - id: logboek-service
          uri: lb://logboek-service
          predicates:
            - Path=/logboek/**
          filters:
            - RewritePath=/logboek/(?<path>.*), /$\{path}


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8062/eureka
  instance:
    hostname: localhost
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 10
